#!/usr/bin/env python3
"""Generate docs/tools.md from the registered MCP tools.

Run from the repo root:  python tools/generate_tool_docs.py
"""

from __future__ import annotations

import asyncio
from pathlib import Path

from lanforge_mcp.config import load_config
from lanforge_mcp.server.app import create_server


def main() -> None:
    cfg = load_config(overrides={"systems": [{"id": "default", "host": "example"}]})
    mcp, _ctx = create_server(cfg)
    tools = asyncio.run(mcp.list_tools())

    groups: dict[str, list] = {}
    for tool in tools:
        tags = sorted(getattr(tool, "tags", None) or [])
        groups.setdefault(tags[0] if tags else "other", []).append(tool)

    lines = [
        "# MCP tool reference",
        "",
        f"{len(tools)} tools, grouped by primary tag. Generated by "
        "`tools/generate_tool_docs.py` — do not edit by hand.",
        "",
    ]
    for tag in sorted(groups):
        lines += [f"## {tag}", ""]
        for tool in sorted(groups[tag], key=lambda t: t.name):
            lines += [f"### `{tool.name}`", "", tool.description or "", ""]
            schema = getattr(tool, "parameters", None) or {}
            props = schema.get("properties", {})
            required = set(schema.get("required", []))
            if props:
                lines += ["| Parameter | Type | Required | Description |", "|---|---|---|---|"]
                for name, prop in props.items():
                    typ = prop.get("type")
                    if not typ and "anyOf" in prop:
                        typ = " or ".join(str(x.get("type", "?")) for x in prop["anyOf"])
                    desc = str(prop.get("description", "")).replace("|", "\\|").replace("\n", " ")
                    lines.append(f"| {name} | {typ or 'any'} | {'yes' if name in required else 'no'} | {desc} |")
                lines.append("")

    out = Path(__file__).resolve().parent.parent / "docs" / "tools.md"
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out} ({len(tools)} tools)")


if __name__ == "__main__":
    main()
